package product.clicklabs.jugnoo.driver.ui.api;

/**
 * Created by Parminder Saini on 26/04/18.
 */
public  enum ApiName {
    GENERATE_OTP,
    VERIFY_OTP,
    GET_CITIES,
    GET_LANGUAGES,
    REGISTER_DRIVER,
    MANUAL_RIDE,
    APPLY_PROMO,
    ADD_CARD_API,
    FETCH_WALLET,
    ADD_CASH_WALLET,
    VEHICLE_MAKE_DATA,
    VEHICLE_MODEL_DATA,
    UPDATE_LUGGAGE_COUNT,
    UPDATE_DOC_FIELDS,
	SHOW_RATE_CARD,
    UPDATE_FARES,
    UPDATE_DRIVER_SERVICES,
    GET_TOLL_DATA,
    UPDATE_TOLL_DATA,
    SEND_EMAIL_INVOICE,
    FETCH_DRIVER_REFERRAL_INFO,
    FETCH_DRIVER_TRACTION_RIDES,
	BRANCH_GENERATE_URL,
	UPDATE_DRIVER_PROPERTY,
    GET_SUBSCRIPTION,
	PAYTM_REQUEST_OTP,
	PAYTM_LOGIN_WITH_OTP,
	PAYTM_REMOVE_WALLET,
	PURCHASE_SUBSCRIPTION,
    UPDATE_GPS_PREFERENCE,
    FETCH_PROGRAMS,
	END_STOP,
	OTP_VIA_CALL
}
