package product.clicklabs.jugnoo.driver.utils;

/**
 * Created by socomo20 on 8/25/15.
 */
public interface FlurryEventNames {

	String
			LOGIN = "login",
			LOGIN_EMAIL_ID = "login email ID",
			LOGIN_PASSWORD = "login password",
			LOGIN_IN_APP = "login in App",
			FORGOT_PASSWORD = "forgot password",
			CHANGE_PASSWORD_ENTER_EMAIL = "change password enter email",
			CHANGE_PASSWORD = "change password",
			MENU = "Menu",
			INVITE_OPENED = "Invite screen opened",
			JUGNOO_ON_OFF = "jugnoo on/off",
			FATAFAT_ENABLE = "Fatafat enable",
			MEALS_ENABLE = "Meals enable",
			RIDES_OPENED = "Rides opened",
			COMPLETE_RIDES_CHECKED = "complete rides checked",
			MISSED_RIDES_CHECKED = "missed rides checked",
			FARE_DETAILS_CHECKED = "fare details checked",
			SUPER_DRIVERS_OPENED = "super drivers opened",
			SHARING_RIDES_OPENED = "Sharing rides opened",
			DAILY_SUPER_DRIVERS = "daily super drivers",
			WEEKLY_SUPER_DRIVERS = "weekly super drivers",
			MONTHLY_SUPER_DRIVERS = "monthly super drivers",
			CHECKING_OVERALL_POSITION = "checking overall position",
			BACK_FROM_SUPER_DRIVERS = "back from super drivers",
			HELP_CHECKED = "help checked",
			SEND_US_AN_EMAIL = "send us an email",
			CALL_US = "call us",
			FAQS = "FAQs",
			ABOUT_JUGNOO = "About Jugnoo",
			TERMS_OF_USE = "Terms of Use",
			PRIVACY_POLICY = "Privacy Policy",
			LOGOUT_FROM_APP = "logout from app",
			RIDE_ACCEPTED = "Ride accepted",
			RIDE_CANCELLED = "Ride cancelled",
			RIDE_CHECKED = "Ride checked",
			RIDE_CHECKED_AND_ACCEPTED = "Ride checked and Accepted",
			RIDE_CHECKED_AND_CANCELLED = "Ride checked and cancelled",
			RIDE_CHECKED_AND_NO_ACTION = "Ride checked and no action",
			ARRIVED_ON_THE_PICK_UP_LOCATION = "Arrived on the pick up location",
			CANCELED_BEFORE_ARRIVING = "Canceled before arriving",
			CANCELLED_BEFORE_ARRIVING_CONFIRMED = "Cancelled before arriving confirmed",
			CANCELLED_BEFORE_ARRIVING_NOT_CONFIRMED = "Cancelled before arriving not confirmed",
			CALLED_CUSTOMER = "Called customer",
			CONFIRMING_ARRIVE_YES = "Confirming Arrive Yes",
			CONFIRMING_ARRIVE_NO = "Confirming Arrive No",
			RIDE_STARTED = "Ride started",
			RIDE_CANCELLED_AFTER_ARRIVING = "Ride cancelled after arriving",
			CALL_CUSTOMER_AFTER_ARRIVING = "Call customer after arriving",
			START_RIDE_CONFIRMED = "Start ride confirmed",
			START_RIDE_NOT_CONFIRMED = "Start ride not confirmed",
			CANCELLED_RIDE_CONFIRMED = "Cancelled ride confirmed",
			CANCELLED_RIDE_NOT_CONFIRMED = "cancelled ride not confirmed",
			CUSTOMER_CALLED_WHEN_RIDE_IN_PROGRESS = "Customer called when ride in progress",
			RIDE_ENDED = "Ride ended",
			END_RIDE_CONFIRMED = "End ride confirmed",
			END_RIDE_NOT_CONFIRMED = "End ride not confirmed",
			OK_ON_FARE_SCREEN = "OK on Fare screen"
					;

}
